name: ESLint Check

on: 
  push:
    branches: [dev]

jobs:
  eslint:
    name: ESLint
    runs-on: WinNote
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - uses: github/super-linter@v4.1.0
        with:
          lint-tools: "eslint"
          eslint-args: "--ext .js --no-ignore --no-inline-config"